language: node_js
node_js: "5"
before_script: npm install -g wcfutils
script: wcfutils
branches:
  only: master
git:
  depth: 5
env:
  global:
    - IDENTIFIER=com.clanunknownsoldiers.plugin.awards.tar
    - FTP_HOST=ftp://thunderstorm.padarom.io
    - secure: "S/KTniF2QOp3bdKtDOy9Gf0XNji+y2xdDAPx8JCAAXp0f3d3uXx0fsLbSKnYNV/CW/ZD5MH0KldsWKbO8N4Xl3e+xk2Ycjl51xSdRTivqgfeCRNP1evyUT7IXCkWtzyTntqxxab82UACKOciXk/XnBGbXvC9PrMw4yeXRQnEwT5jy5qD6vLxAmCFkIrcNrN7nU3+6zTOKVA9PL9kmxHe7gfLLeYuol063NQ43kwvoKP2Ww9l/4B31YPrj262pgzh5b3dXxdjRscfzcO1P3D7GUascRp6YDT+Ajfi2dKEfvdnzO6xmltsKf7ivcZltTpGSIC4LVfOMF5/1GeUY7dlbUY+zVsz9MYv8/d4Lvxmy/JRlqCqoC+2fb/s5xDLU1B+s/v33Xa4UewgmG3YSIcHvOuFu6Nw6gUtmQN6XuUh86p7Asvqb0bvjVUWWY69z3PlwNbv/OiWkr0PsAO4Cn3qWE79xQHJuJT4tvgF3c7RVmWP63t5QFttu8XiEKYwP4xue2zOQHr3d+1+5HoBZGMv+BwEhrbo9BQWiHThZDnpVVdazZwpM0+KPPYxb1rn74BZDmJybjAFjsJGUOQ08JhMr9F6Zv6nbFRgSVKKEZLj6DxOO9sa9VimuQLEFZJC4t7YVYufIT9id5A4O7ZhXAiu+mfZH+u+pnAY4+o3hVAbeiM="
    - secure: "pcA2V2V3+UW8XZTxMBTr74bwHk7WqtVwS46LObhYCnEdfE2/RTePHOluo9zQ0njhdHizvGbUTwPi61QSnsrarrulXaOHqJLoj9PIQ3VXBwEoZlcPheXx0jHoJ00L+ziZbw+F4icWw33/sIeYWZQ/V0IE58LXBgkABItGZfvN1obzrZGrV1JDyFVePZWczEWjCa6ljCRoZ5DWQETjagBmUOAReovngJy+AAaHiw9CGo2/93kgp3kjqla0Q2zlKntTaSSO5awzmoMQHER1TqEKmiyCnJqgL9edmirzYPtqXzC4E3PoFRF0sMI6oqze/IbuDxirfO8jDrhG3Eb3UbPSHxfP9yP/dP32X08hALgY9coltXNP3SoPwQi7YoqBCicvOoOP9V/6kxHDjqL/JT6S72GYiR4E9TD5L0PZdGYwuEyqKlU7Z81P22FfU1yNjFulep1Ecp4+0FK32nY5Hw+oDVQkRrCYMi89GDxTUggQCAsx5TAuUZpCVubNFyScNUaVU1kWJdDVgHHJ6syOaY7W16OKOW75YDHDhceknDfLYlmnq+VB+ekv0REq6zQVJT1/Ox+Qu/dhdSmrtVZyACfGv98nWFMtuf7xQK6coN/XDgkvbj6H7SuVOaOHMs6OePjH7WxITafzfHRHQdtWlD0C1zwDbdAG+IgpidwmTqz9bW0="
notifications:
      email: false

after_success: curl --ftp-create-dirs -T $IDENTIFIER -u $FTP_USER:$FTP_PASSWORD $FTP_HOST
