language: node_js
node_js: '8'
before_script: npm install -g wspackager
script: wspackager
branches:
  only: master
git:
  depth: 5
env:
  global:
  - IDENTIFIER=com.clanunknownsoldiers.plugin.pages.tar
  - FTP_HOST=ftp://thunderstorm.unkso.com/
  - secure: WHiTkJ10jrzmSVY+Dv6mj54LOXxMcjnRtZGRWicqyrKiyeTnoL09A4fP7vSfBLfaoWsx4/JygHyDPxHX3bHSTyLENg1uzhY3OQIxtIy61XmMqEQ3edZ7m6VN5UsZGmhTTsjPpvUFxSPni5mPQdH8Y7HHhVRFNgyL4/NUhPn/25IlragYEwby+YNEDqZuaHZUg4oy7rQ7a5znLWMgav876LE3tLzxX3SLBpLZ4saAsgxSGrD+u0xxWyoI/PnezeOTtVexK4DknbQea/fLkezvoPD8JeCskk3Jnj8tGPB3Dh8tTfVPhxQq8HKxUuVm/My0T+7cXYR65FSs/VwH3ri5lFie9KQv6ap3BW8mHf2gDNFdNHcMjURqhyv5cGebYI/Ub/EzqUq5ZeLonorq3jz6jhPqcLZeC7Dpg+hJdbzYxOzSTlyJZneRPp+VG83Xe7PuQ30UNa5qQKmhhVP0VHFRQc80q2nPnznpKbDttMUpq/DSt3b+AU8+MlHusmEzj3/cNf+55jmGw6lP1u36j4PI4VEnZtGvbGuBOd7RYm+crqdXKkcP17UZTupAI6f24hfSRMSLPCM/FaWbDzF8mh2LRx043plcqUKz119R8UUNCXxhjYjBB0zITyHhfylL4XCbRn4DC4+xxd5oCMg6DOPrs7w3uSVVTrEgyUF5Jt4NsJM=
  - secure: m0MXozSrjVfqGlidYpVpk3S0KsTYBhTPNiD/M4dRffxTkulSWhCQV44ZS5aPgEYRN6+NjZZdWJ0oDkgZc6/3/K6A7WF4QbocMiztaKNpCeIqKcc5uwP7ZO5MWvKmEtoW1mEhY+4KRG7iQYyD0204G7VB9PDS49vi2zjALLD+3fvHmLRCYgi57Fdl9S0a0VVbxB7N/+pXAAeKDL7bObAwflSXWXTRES6VdHmQCHUgdSFgEwhIBhtzPhcwli0WuP9jzAj6pz4bFnWl9UTh+v7z1EF+fBvEntNP4qt5KBz/pM17RbwzbifGzTKquqandoi4v1NkJx317dNC64OK+dPlJ6T9J0YvK3r+tkosdAqs+m48V0STHvEML2QyLqpssnf6IeNlpR1dfo7I5H9eUoX7GToG6Q8ZfxhvCJgJiu5Dny3w7XF11ySyiuOAIDNLxq44bNn2YyJLiDGbS+ULKeKxcxM6s+iG7nAbUx4h2vpGM2451L0NX3Y0QWkhQuhqr7No8/Q8K+qhoBT/2jVF8E+gyaie5hZk0Ie6ojJvt7rqkXMmJkHbsCG9dNXqzGFjIzasUwnhIcTCG/V36Yt7XdgPe7+XGyydw0vpzpy0a0oh+e7YCcSy3EE/XMEon234P4OqpcmlaPYLhen6vmXHuKgissDyZm3+zkcvUXGDiqF5rRk=
notifications:
  email: false
after_success: curl --ftp-create-dirs -T $IDENTIFIER -u $FTP_USER:$FTP_PASSWORD $FTP_HOST
